---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: vasanth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: replicated-web
  template:
    metadata:
      labels:
        app: replicated-web
    spec:
      nodeName: "insert-your-node-name-here"
      containers:
        - name: nginx-container
          image: nginx:alpine
          ports:
            - containerPort: 80
