---
apiVersion: v1
kind: ReplicationController
metadata:
  name: test-replication-controller
  namespace: vasanth
spec:
  replicas: 3
  selector:
    app: replicated-web
  template:
    metadata:
      labels:
        app: replicated-web
    spec:
      # Optional: Forces all 3 replicas to run on this exact node
      nodeName: "insert-your-node-name-here" 
      containers:
        - name: nginx-container
          image: nginx:alpine
          ports:
            - containerPort: 80
